"""empty message

Revision ID: 580bb9d1bf72
Revises: 1a7f209aa772
Create Date: 2019-07-16 08:51:20.986924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580bb9d1bf72'
down_revision = '1a7f209aa772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'create_time')
    # ### end Alembic commands ###
