"""empty message

Revision ID: 90d41d2f1746
Revises: b5ac5ef93a26
Create Date: 2019-07-13 19:53:59.572889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90d41d2f1746'
down_revision = 'b5ac5ef93a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('cms_role', sa.Column('permissions', sa.Integer(), nullable=True))
    op.drop_column('cms_role', 'permission')
    op.drop_column('cms_role', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role', sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('cms_role', sa.Column('permission', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('cms_role', 'permissions')
    op.drop_column('cms_role', 'name')
    # ### end Alembic commands ###
